apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: koji
parameters:
  - name: KOJI_DOJO_REMOTE
    displayName: Remote for koji dojo
    value: https://github.com/LynnZhuang/koji-dojo
    required: true
  - name: KOJI_DOJO_BRANCH
    displayName: koji dojo branch
    value: master
    required: true
  - name: KOJI_GIT_COMMIT
    displayName: koji git commit
    value: ${KOJI_GIT_COMMIT}
    required: true
  - name: KOJI_IMAGESTREAM_NAMESPACE
    displayName: Namespace of ImageStream for koji hub container images
    required: false
  - name: KOJI_IMAGE_TAG
    displayName: Tag of resulting image
    value: latest
    required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: koji-dojo-config
  data:
    koji.git.url: https://pagure.io/koji.git
    koji.git.branch: master
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: hub-koji-claim
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: glusterfs-storage
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: hub
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: hub:"${KOJI_IMAGE_TAG}"
        namespace: "${KOJI_IMAGESTREAM_NAMESPACE}"
    postCommit: {}
    resources:
      requests:
        memory: "768Mi"
        cpu: "300m"
      limits:
       memory: "1Gi"
       cpu: "500m"
    runPolicy: Serial
    source:
      contextDir: hub
      git:
        ref: "${KOJI_DOJO_BRANCH}"
        uri: "${KOJI_DOJO_REMOTE}"
      type: Git
    strategy:
      dockerStrategy:
        noCache: true
        forcePull: true
        # dockerfilePath: hub/Dockerfile
      type: Docker
    triggers: []
  status:
    lastVersion: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    generation: 1
    name: koji-hub
